\ include gpio.f
\ inlcude time.f

DECIMAL

\ VSS     GND
\ VDD     +5V
\ VO      POT
25 CONSTANT LCD_RS      
\ RW      GND
24 CONSTANT LCD_E       
12 CONSTANT LCD_D0      
4  CONSTANT LCD_D1      
27 CONSTANT LCD_D2      
16 CONSTANT LCD_D3      
23 CONSTANT LCD_D4      
17 CONSTANT LCD_D5      
18 CONSTANT LCD_D6      
22 CONSTANT LCD_D7      
\ A       +5V
\ K       GND

1 CONSTANT LCD_CHR 
0 CONSTANT LCD_CMD 

: LCD_SETUP 
    LCD_E  GPIO MODE OUTPUT
    LCD_RS GPIO MODE OUTPUT
    LCD_D0 GPIO MODE OUTPUT
    LCD_D1 GPIO MODE OUTPUT
    LCD_D2 GPIO MODE OUTPUT
    LCD_D3 GPIO MODE OUTPUT
    LCD_D4 GPIO MODE OUTPUT
    LCD_D5 GPIO MODE OUTPUT
    LCD_D6 GPIO MODE OUTPUT
    LCD_D7 GPIO MODE OUTPUT
;


: +ENABLE_SIGNAL LCD_E GPIO ON ;

: -ENABLE_SIGNAL LCD_E GPIO OFF ;

: LCD_PULSE 500 USEC DELAY +ENABLE_SIGNAL 500 USEC DELAY -ENABLE_SIGNAL 500 USEC DELAY ;

: LCD_D_RESET
    LCD_E GPIO OFF
    LCD_D0 GPIO OFF
    LCD_D1 GPIO OFF
    LCD_D2 GPIO OFF
    LCD_D3 GPIO OFF
    LCD_D4 GPIO OFF
    LCD_D5 GPIO OFF
    LCD_D6 GPIO OFF
    LCD_D7 GPIO OFF
;

HEX
: LCD_WRITE
    0> IF LCD_RS GPIO ON ELSE LCD_RS GPIO OFF THEN 

    80 /mod 0> IF LCD_D7 GPIO ON ELSE LCD_D7 GPIO OFF THEN
    40 /mod 0> IF LCD_D6 GPIO ON ELSE LCD_D6 GPIO OFF THEN
    20 /mod 0> IF LCD_D5 GPIO ON ELSE LCD_D5 GPIO OFF THEN
    10 /mod 0> IF LCD_D4 GPIO ON ELSE LCD_D4 GPIO OFF THEN
    08 /mod 0> IF LCD_D3 GPIO ON ELSE LCD_D3 GPIO OFF THEN
    04 /mod 0> IF LCD_D2 GPIO ON ELSE LCD_D2 GPIO OFF THEN
    02 /mod 0> IF LCD_D1 GPIO ON ELSE LCD_D1 GPIO OFF THEN
            0> IF LCD_D0 GPIO ON ELSE LCD_D0 GPIO OFF THEN
    
    LCD_PULSE
;

HEX
: LCD_WRITE_4
    0> IF LCD_RS GPIO ON ELSE LCD_RS GPIO OFF THEN 
    
    \ set high bits
    80 /mod 0> IF LCD_D7 GPIO ON ELSE LCD_D7 GPIO OFF THEN
    40 /mod 0> IF LCD_D6 GPIO ON ELSE LCD_D6 GPIO OFF THEN
    20 /mod 0> IF LCD_D5 GPIO ON ELSE LCD_D5 GPIO OFF THEN
    10 /mod 0> IF LCD_D4 GPIO ON ELSE LCD_D4 GPIO OFF THEN
    
    LCD_PULSE
    
    \ set low bits
    08 /mod 0> IF LCD_D7 GPIO ON ELSE LCD_D7 GPIO OFF THEN
    04 /mod 0> IF LCD_D6 GPIO ON ELSE LCD_D6 GPIO OFF THEN
    02 /mod 0> IF LCD_D5 GPIO ON ELSE LCD_D5 GPIO OFF THEN
            0> IF LCD_D4 GPIO ON ELSE LCD_D4 GPIO OFF THEN
    
    LCD_PULSE
;

HEX
: INIT
    33 LCD_CMD LCD_WRITE
    6 LCD_CMD LCD_WRITE
    C LCD_CMD LCD_WRITE
    38 LCD_CMD LCD_WRITE
    1 LCD_CMD LCD_WRITE
;

