\ include gpio.f
\ inlcude time.f
\ inlcude lcd.f

DECIMAL

20 CONSTANT RCAR
21 CONSTANT YCAR
26 CONSTANT GCAR

19 CONSTANT RPED
13 CONSTANT YPED
6  CONSTANT GPED

5  CONSTANT BUTTON

: RED RCAR RPED ;
: YELLOW YCAR YPED ;
: GREEN GCAR GPED ;

: CAR DROP ;
: PEDESTRIAN SWAP DROP ;

\ SEMSETUP ( -- ) set the output state to the semaphore's GPIO.
: SEMSETUP 
    RED CAR GPFSELOUT!
    YELLOW CAR GPFSELOUT!
    GREEN CAR GPFSELOUT!
    RED PEDESTRIAN GPFSELOUT!
    YELLOW PEDESTRIAN GPFSELOUT!
    GREEN PEDESTRIAN GPFSELOUT!
;

\ SEMINIT ( -- ) initializes the state of the semaphore's LEDs.
: SEMINIT  
    RED CAR GPOFF! 
    YELLOW CAR GPOFF! 
    GREEN CAR GPON! 
    RED PEDESTRIAN GPON!
    YELLOW PEDESTRIAN GPOFF! 
    GREEN PEDESTRIAN GPOFF! 
;
